apiVersion: app.reload.com/v1alpha1
kind: AppService
metadata:
  name: example-appservice
spec:
  # Add fields here
  size: 1
  # static configmap which will not trigger hot-reload
  static:
    - mystatic
  # dynamic configmap which will trigger hot-reload
  dynamic:
   - default-conf
   - index.html
   - index-dev.html
  selector:
    hot-reload-policy: delete

