apiVersion: app.reload.com/v1alpha1
kind: AppService
metadata:
  name: example-appservice
spec:
  # Add fields here
  size: 1
  static:
    - test.html
  reload:
   - index.html
   - 404.html
  selector:
    hot-reload-policy: delete

