apiVersion: apps/v1
kind: Deployment
metadata:
  name: configmap-reload-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: configmap-reload-operator
  template:
    metadata:
      labels:
        name: configmap-reload-operator
    spec:
      serviceAccountName: configmap-reload-operator
      containers:
        - name: configmap-reload-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - configmap-reload-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "configmap-reload-operator"
