apiVersion: v1
data:
  redis-config: |
    maxmemory 2mb
    maxmemory-policy allkeys-lru
kind: ConfigMap
metadata:
  name: example-config
  namespace: default
  labels:
      hot-reload-policy: delete
      test-22: dd
